export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Footer } from "./Footer";
export { default as Extra } from "./Extra";
export { default as About1 } from "./AboutSec";
export { default as Testimonials } from "./Testimonials";
export { default as Offers } from "./Offers";
export { default as Eco } from "./Eco";
export { default as Gallary } from "./Gallary";
